# CloudFormation Template for SkillBridge User Service DynamoDB Tables

AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB tables for SkillBridge User Service'

Parameters:
  Environment:
    Type: String
    Default: college
    Description: Environment name for college assignment
    AllowedValues: [college, dev]
  
  ProjectName:
    Type: String
    Default: skillbridge
    Description: Project name for resource naming

Resources:
  # Users Table - Extended version with user profile data
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-users-${Environment}'
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        - AttributeName: domain
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: type-index
          KeySchema:
            - AttributeName: type
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: domain-index
          KeySchema:
            - AttributeName: domain
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: user-service

  # Bookings Table
  BookingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-bookings-${Environment}'
      AttributeDefinitions:
        - AttributeName: bookingId
          AttributeType: S
        - AttributeName: mentorId
          AttributeType: S
        - AttributeName: menteeId
          AttributeType: S
      KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: mentor-index
          KeySchema:
            - AttributeName: mentorId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: mentee-index
          KeySchema:
            - AttributeName: menteeId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: user-service

  # Messages Table
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-messages-${Environment}'
      AttributeDefinitions:
        - AttributeName: messageId
          AttributeType: S
        - AttributeName: conversationId
          AttributeType: S
      KeySchema:
        - AttributeName: messageId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: conversation-index
          KeySchema:
            - AttributeName: conversationId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: user-service

  # Code Reviews Table
  CodeReviewsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-code-reviews-${Environment}'
      AttributeDefinitions:
        - AttributeName: reviewId
          AttributeType: S
        - AttributeName: mentorId
          AttributeType: S
        - AttributeName: menteeId
          AttributeType: S
      KeySchema:
        - AttributeName: reviewId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: mentor-reviews-index
          KeySchema:
            - AttributeName: mentorId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: mentee-reviews-index
          KeySchema:
            - AttributeName: menteeId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Service
          Value: user-service

Outputs:
  UsersTableName:
    Description: Name of the Users DynamoDB table
    Value: !Ref UsersTable
    Export:
      Name: !Sub '${AWS::StackName}-UsersTable'
  
  UsersTableArn:
    Description: ARN of the Users DynamoDB table
    Value: !GetAtt UsersTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UsersTableArn'
  
  BookingsTableName:
    Description: Name of the Bookings DynamoDB table
    Value: !Ref BookingsTable
    Export:
      Name: !Sub '${AWS::StackName}-BookingsTable'
  
  MessagesTableName:
    Description: Name of the Messages DynamoDB table
    Value: !Ref MessagesTable
    Export:
      Name: !Sub '${AWS::StackName}-MessagesTable'
  
  CodeReviewsTableName:
    Description: Name of the Code Reviews DynamoDB table
    Value: !Ref CodeReviewsTable
    Export:
      Name: !Sub '${AWS::StackName}-CodeReviewsTable'
  
  EmailIndexName:
    Description: Name of the email GSI
    Value: email-index
    Export:
      Name: !Sub '${AWS::StackName}-EmailIndex'
  
  TypeIndexName:
    Description: Name of the type GSI
    Value: type-index
    Export:
      Name: !Sub '${AWS::StackName}-TypeIndex'
  
  DomainIndexName:
    Description: Name of the domain GSI
    Value: domain-index
    Export:
      Name: !Sub '${AWS::StackName}-DomainIndex'