version: '3.8'

services:
  # Frontend App (Angular)
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "4200:80"  # Alternative port for development
    networks:
      - skillbridge-network
    depends_on:
      - auth-service
      - user-service
      - booking-service
      - code-review-service
      - messaging-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Authentication Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    networks:
      - skillbridge-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Booking Service
  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./booking-service/.env
    networks:
      - skillbridge-network
    depends_on:
      - auth-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Code Review Service
  code-review-service:
    build:
      context: ./code-review-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ./code-review-service/.env
    networks:
      - skillbridge-network
    depends_on:
      - auth-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Messaging Service (WebSocket + REST)
  messaging-service:
    build:
      context: ./messaging-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    env_file:
      - ./messaging-service/.env
    networks:
      - skillbridge-network
    depends_on:
      - auth-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    env_file:
      - ./user-service/.env
    networks:
      - skillbridge-network
    depends_on:
      - auth-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  skillbridge-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  # Optional: If you need persistent volumes for logs or temporary files
  app-logs:
    driver: local